In [1]:
# Sanity check — does the env work?
import sys
import pandas as pd
import numpy as np
import matplotlib
import seaborn as sns
import plotly

print(f"Python:     {sys.version.split()[0]}")
print(f"pandas:     {pd.__version__}")
print(f"numpy:      {np.__version__}")
print(f"matplotlib: {matplotlib.__version__}")
print(f"seaborn:    {sns.__version__}")
print(f"plotly:     {plotly.__version__}")

Python:     3.11.15
pandas:     3.0.3
numpy:      2.4.6
matplotlib: 3.10.9
seaborn:    0.13.2
plotly:     6.6.0

## Step 3 : Load the data + first peek

In [2]:
from pathlib import Path

# Define paths relative to the notebook location
# Path.cwd() = where the notebook lives (notebooks/)
# .parent = repo root
REPO = Path.cwd().parent
DATA_RAW = REPO / "data" / "raw"

# Confirm the files we expect are there
print("Files in data/raw:")
for f in sorted(DATA_RAW.iterdir()):
    print(f"  {f.name}  ({f.stat().st_size:,} bytes)")

Files in data/raw:
  constituency_master.csv  (8,595 bytes)
  tn_2021_results.csv  (246,553 bytes)
  tn_2026_results.csv  (234,607 bytes)

In [3]:
import pandas as pd

df_2021 = pd.read_csv(DATA_RAW / "tn_2021_results.csv")
df_2026 = pd.read_csv(DATA_RAW / "tn_2026_results.csv")
df_master = pd.read_csv(DATA_RAW / "constituency_master.csv")

print(f"2021 results:  {df_2021.shape[0]:>5} rows × {df_2021.shape[1]} cols")
print(f"2026 results:  {df_2026.shape[0]:>5} rows × {df_2026.shape[1]} cols")
print(f"AC master:     {df_master.shape[0]:>5} rows × {df_master.shape[1]} cols")

2021 results:   4232 rows × 8 cols
2026 results:   4257 rows × 8 cols
AC master:       234 rows × 5 cols

In [4]:
df_2021.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro
1,Gummidipundi,1,PRAKASH M,PMK,75514,78.08,GEN,Chennai Metro
2,Gummidipundi,1,USHA,NTK,11701,78.08,GEN,Chennai Metro
3,Gummidipundi,1,DILLIY K.M,DMDK,2576,78.08,GEN,Chennai Metro
4,Gummidipundi,1,None Of The Above,NOTA,1783,78.08,GEN,Chennai Metro

In [5]:
df_2026.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro
1,Gummidipoondi,1,SUDHAKAR.V,AIADMK,66375,NaN,GEN,Chennai Metro
2,Gummidipoondi,1,T.J.GOVINDARAJAN,DMK,62492,NaN,GEN,Chennai Metro
3,Gummidipoondi,1,"R.SRIDAR. B.L.,",NTK,4756,NaN,GEN,Chennai Metro
4,Gummidipoondi,1,NOTA,NOTA,937,NaN,GEN,Chennai Metro

In [6]:
df_master.head()

   ac_number  constituency    district         region reserved
0          1  Gummidipundi  Tiruvallur  Chennai Metro      GEN
1          2       Ponneri  Tiruvallur  Chennai Metro       SC
2          3     Tiruttani  Tiruvallur  Chennai Metro      GEN
3          4   Thiruvallur  Tiruvallur  Chennai Metro      GEN
4          5   Poonamallee  Tiruvallur  Chennai Metro       SC

In [7]:
df_2021.info()

<class 'pandas.DataFrame'>
RangeIndex: 4232 entries, 0 to 4231
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   constituency  4232 non-null   str
 1   ac_number     4232 non-null   int64
 2   candidate     4232 non-null   str
 3   party         4232 non-null   str
 4   votes         4232 non-null   int64
 5   turnout       4232 non-null   float64
 6   reserved      4232 non-null   str
 7   region        4232 non-null   str
dtypes: float64(1), int64(2), str(5)
memory usage: 427.0 KB

In [8]:
df_2026.info()

<class 'pandas.DataFrame'>
RangeIndex: 4257 entries, 0 to 4256
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   constituency  4257 non-null   str
 1   ac_number     4257 non-null   int64
 2   candidate     4257 non-null   str
 3   party         4257 non-null   str
 4   votes         4257 non-null   int64
 5   turnout       0 non-null      float64
 6   reserved      4257 non-null   str
 7   region        4257 non-null   str
dtypes: float64(1), int64(2), str(5)
memory usage: 438.1 KB

In [9]:
df_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ac_number     234 non-null    int64
 1   constituency  234 non-null    str
 2   district      234 non-null    str
 3   region        234 non-null    str
 4   reserved      234 non-null    str
dtypes: int64(1), str(4)
memory usage: 15.9 KB

In [10]:
df_2021.describe()

         ac_number          votes      turnout
count  4232.000000    4232.000000  4232.000000
mean    115.253544   10925.447070    73.038514
std      68.316849   27152.954736     7.726449
min       1.000000       2.000000    55.510000
25%      56.000000     121.000000    68.080000
50%     116.000000     336.500000    74.770000
75%     177.000000    1966.500000    78.850000
max     234.000000  171558.000000    87.370000

In [11]:
df_2026.describe()

         ac_number          votes  turnout
count  4257.000000    4257.000000      0.0
mean    112.949965   11586.591731      NaN
std      68.293502   25786.948660      NaN
min       1.000000       2.000000      NaN
25%      54.000000     122.000000      NaN
50%     113.000000     271.000000      NaN
75%     172.000000    1031.000000      NaN
max     234.000000  220382.000000      NaN

In [12]:
# Unique constituency count in each year
print(f"Unique constituencies in 2021: {df_2021['ac_number'].nunique()}")
print(f"Unique constituencies in 2026: {df_2026['ac_number'].nunique()}")
print(f"Unique constituencies in master: {df_master['ac_number'].nunique()}")
print()

# Unique parties contesting
print(f"Unique parties in 2021: {df_2021['party'].nunique()}")
print(f"Unique parties in 2026: {df_2026['party'].nunique()}")
print()

# Candidates per constituency (avg)
print(f"Avg candidates per AC in 2021: {df_2021.shape[0] / 234:.1f}")
print(f"Avg candidates per AC in 2026: {df_2026.shape[0] / 234:.1f}")

Unique constituencies in 2021: 234
Unique constituencies in 2026: 234
Unique constituencies in master: 234

Unique parties in 2021: 109
Unique parties in 2026: 105

Avg candidates per AC in 2021: 18.1
Avg candidates per AC in 2026: 18.2

## Step 4 : Data Quality Checks

In [14]:
# 4.1 Null check — are there any unexpected blanks?
print("=== NULL COUNTS ===\n")
print("--- 2021 ---")
print(df_2021.isnull().sum())
print("\n--- 2026 ---")
print(df_2026.isnull().sum())
print("\n--- Master ---")
print(df_master.isnull().sum())

=== NULL COUNTS ===

--- 2021 ---
constituency    0
ac_number       0
candidate       0
party           0
votes           0
turnout         0
reserved        0
region          0
dtype: int64

--- 2026 ---
constituency       0
ac_number          0
candidate          0
party              0
votes              0
turnout         4257
reserved           0
region             0
dtype: int64

--- Master ---
ac_number       0
constituency    0
district        0
region          0
reserved        0
dtype: int64

In [21]:
# 4.2 Duplicate check — any row appearing twice?

# A real duplicate = same candidate, same AC, in the same year
print(f"2021 duplicate (ac_number, candidate): {df_2021.duplicated(subset=['ac_number','candidate']).sum()}")
print(f"2026 duplicate (ac_number, candidate): {df_2026.duplicated(subset=['ac_number','candidate']).sum()}")
print(f"Master duplicate (ac_number):          {df_master.duplicated(subset=['ac_number']).sum()}")


# Show the actual duplicate rows in 2026 to inspect them
print("=== 2026 duplicates ===")
dupes_26 = df_2026[df_2026.duplicated(subset=['ac_number','candidate'], keep=False)].sort_values(['ac_number','candidate'])
print(dupes_26[['ac_number','constituency','candidate','party','votes']].to_string(index=False))

print("\n\n=== 2021 duplicates ===")
dupes_21 = df_2021[df_2021.duplicated(subset=['ac_number','candidate'], keep=False)].sort_values(['ac_number','candidate'])
print(dupes_21[['ac_number','constituency','candidate','party','votes']].to_string(index=False))

2021 duplicate (ac_number, candidate): 14
2026 duplicate (ac_number, candidate): 25
Master duplicate (ac_number):          0
=== 2026 duplicates ===
 ac_number           constituency       candidate             party  votes
        16                 Egmore        RAJMOHAN               TVK  53901
        16                 Egmore        RAJMOHAN               IND     92
        17              Royapuram    D. JAYAKUMAR            AIADMK  18420
        17              Royapuram    D. JAYAKUMAR               IND     76
        19 Chepauk-Thiruvallikeni       SELVAM. K               IND     43
        19 Chepauk-Thiruvallikeni       SELVAM. K               IND     37
        28                Alandur        M.HARISH               TVK 112205
        28                Alandur        M.HARISH               IND    853
        28                Alandur     S.SARAVANAN            AIADMK  52243
        28                Alandur     S.SARAVANAN               IND     76
        37           Kancheepuram V. SOMASUNDARAM            AIADMK  75862
        37           Kancheepuram V. SOMASUNDARAM               IND     78
        58             Pennagaram      SELVAM. V.               PMK  78075
        58             Pennagaram      SELVAM. V.               IND    202
        64           Kilpennathur  RAMACHANDRAN.K               IND     65
        64           Kilpennathur  RAMACHANDRAN.K               IND     33
        66                  Polur    SARAVANAN. P              DMDK  67734
        66                  Polur    SARAVANAN. P               IND    349
        67                  Arani  MAHALAKSHMI. G               IND    359
        67                  Arani  MAHALAKSHMI. G               IND    117
        74             Viluppuram    LAKSHMANAN R               DMK  72982
        74             Viluppuram    LAKSHMANAN R               IND    243
        74             Viluppuram    LAKSHMANAN R               IND    175
        74             Viluppuram        VIJAYA M               IND    141
        74             Viluppuram        VIJAYA M               IND     93
        80           Kallakurichi       MALATHI K               VCK  77666
        80           Kallakurichi       MALATHI K               IND    179
        90          Salem (South)   LOGANATHAN. M               DMK  58002
        90          Salem (South)   LOGANATHAN. M               IND    165
        90          Salem (South)   LOGANATHAN. M               IND     71
       114       Tiruppur (South)     DINESHKUMAR               IND    235
       114       Tiruppur (South)     DINESHKUMAR               IND    203
       120     Coimbatore (South) V. SENTHILKUMAR               TVK  57453
       120     Coimbatore (South) V. SENTHILKUMAR               IND     92
       131                 Natham   VIJAYAKUMAR S               IND    465
       131                 Natham   VIJAYAKUMAR S Puthiya Tamilagam    103
       139              Srirangam     S. DURAIRAJ               DMK  69645
       139              Srirangam     S. DURAIRAJ               IND    298
       142          Thiruverumbur        KUMAR. P            AIADMK  29473
       142          Thiruverumbur        KUMAR. P               IND     48
       146              Thuraiyur        E.SAROJA            AIADMK  56649
       146              Thuraiyur        E.SAROJA               IND     95
       179            Viralimalai    VEERAMANI. M               IND     90
       179            Viralimalai    VEERAMANI. M               IND     56
       180            Pudukkottai   C. KARUPPAIAH               IND    233
       180            Pudukkottai   C. KARUPPAIAH               IND    112
       201                 Cumbum      PRAKASH P.               IND    254
       201                 Cumbum      PRAKASH P.               IND    181


=== 2021 duplicates ===
 ac_number constituency       candidate  party  votes
         1 Gummidipundi       PRAKASH M    PMK  75514
         1 Gummidipundi       PRAKASH M    IND    196
         3    Tiruttani        Chandran    IND     60
         3    Tiruttani        Chandran    IND     46
        52       Bargur      KRISHNAN A AIADMK  84642
        52       Bargur      KRISHNAN A    IND    107
        61        Harur       MURUGAN.R   AMMK  14327
        61        Harur       MURUGAN.R    IND    521
        65 Kalasapakkam Panneerselvam.V AIADMK  84912
        65 Kalasapakkam Panneerselvam.V    IND    239
        67        Arani  S.RAMACHANDRAN AIADMK 102961
        67        Arani  S.RAMACHANDRAN    IND    134
        71       Mailam    MASILAMANI V    IND    807
        71       Mailam    MASILAMANI V    IND    524
        84       Omalur          R.MANI AIADMK 142488
        84       Omalur          R.MANI    IND    284
       121  Singanallur      Karthik, N    DMK  70390
       121  Singanallur      Karthik, N    IND    135
       147   Perambalur   RAJENDRAN, K.   DMDK   2932
       147   Perambalur   RAJENDRAN, K.    BSP    520
       181   Thirumayam    K.SELVAKUMAR    IND  15144
       181   Thirumayam    K.SELVAKUMAR    IND     54
       181   Thirumayam    M.SELVAKUMAR    IND    456
       181   Thirumayam    M.SELVAKUMAR    IND    315
       181   Thirumayam    M.SELVAKUMAR    IND     87
       202  Rajapalayam    KALIMUTHU K.   AMMK   7660
       202  Rajapalayam    KALIMUTHU K.    IND    120

In [16]:
# 4.3 AC number completeness — are all 234 ACs covered?
# Expected set: {1, 2, 3, ..., 234}
expected = set(range(1, 235))

ac_21 = set(df_2021['ac_number'].unique())
ac_26 = set(df_2026['ac_number'].unique())
ac_master = set(df_master['ac_number'].unique())

print(f"Missing ACs in 2021: {sorted(expected - ac_21) or 'None ✅'}")
print(f"Missing ACs in 2026: {sorted(expected - ac_26) or 'None ✅'}")
print(f"Missing ACs in master: {sorted(expected - ac_master) or 'None ✅'}")

Missing ACs in 2021: None ✅
Missing ACs in 2026: None ✅
Missing ACs in master: None ✅

In [17]:
# 4.4 Reserved-seat sanity — does it match the brief?
# Use drop_duplicates so each AC counts once, not once per candidate
res_21 = df_2021.drop_duplicates('ac_number')['reserved'].value_counts().to_dict()
res_26 = df_2026.drop_duplicates('ac_number')['reserved'].value_counts().to_dict()
res_master = df_master['reserved'].value_counts().to_dict()

print(f"2021 reserved counts: {res_21}")
print(f"2026 reserved counts: {res_26}")
print(f"Master reserved counts: {res_master}")

2021 reserved counts: {'GEN': 188, 'SC': 44, 'ST': 2}
2026 reserved counts: {'GEN': 188, 'SC': 44, 'ST': 2}
Master reserved counts: {'GEN': 188, 'SC': 44, 'ST': 2}

In [18]:
#4.5 Party-name consistency — the silent killer
parties_21 = set(df_2021['party'].unique())
parties_26 = set(df_2026['party'].unique())

print(f"Parties in 2021 only: {len(parties_21 - parties_26)}")
print(sorted(parties_21 - parties_26))
print()
print(f"Parties in 2026 only: {len(parties_26 - parties_21)}")
print(sorted(parties_26 - parties_21))
print()
print(f"Common to both: {len(parties_21 & parties_26)}")

Parties in 2021 only: 61
['AIMIM', 'AISMK', 'AITC', 'Akhil Bharat Hindu Mahasabha', 'Akhila India Jananayaka Makkal Katchi (Dr. Isaac)', 'Akila India Vallalar Peravai', 'All  India  Pattali  Munnetra Katchi', 'All India MGR Makkal Munnetra Kazhagam', 'All Pensioner’s Party', 'Ambedkar Political Party', 'Ambedkarite Party of India', 'Anaithu Makkal Arasiyal Katchi', 'Anaithu Makkal Munnetra Kazhagam', 'Anaithu Makkal Puratchi Katchi', 'Anaithu Ulaga Tamilargal Munnetra Kalagam', 'Anna Dravidar Kazhagam', 'Anna MGR Dravida Munnetra Kazhagam', 'BSP', 'Bhartiya Manavadhikaar Federal Party', 'CPI(ML)(L)', 'Desa Makkal Munnetrak Kazhgam', 'Desiya Sirupanmayinar Makkal Iyakkam', 'Dhesiya Makkal Kazhagam', 'Dravida Murpokku Makkal Katchi', 'Hindustan Janta Party', 'IJK', 'Ilantamilar Munnani Kazhagam', 'India Dravida Makkal Munnetra Katchi', 'JD(S)', 'Kongu  Desa  Marumalarchi  Makkal  Katchi', 'LJP', 'MNM', 'Mahathma Makkal Munnetra Kazhakam', 'Makkal Munnetra Peravai', 'Makkal Sananayaga Kudiyarasu Katchi,', 'Makkal Thilagam Munnetra Kazhagam,', 'Manitha Urimaigal Kalaagam', 'My India Party', 'NCP', 'NPP', 'Nam India Naam Indiyar Katchi', 'National Democratic Party of South India', 'New Generation People’s Party', "People's Party of India(secular)", 'RJD', 'RPI(A)', 'RSPS', 'Rashtriya Ulama Council', 'Republican Party of India  (Sivaraj)', 'SDPI', 'SHS', 'SP', 'SUCI', 'South India Forward Bloc', 'Tamilaga Makkal Thannurimai Katchi', 'Tamilnadu Makkal Nalvazhvu Periyakkam', 'Tipu Sultan Party', 'Ulaga Makkal Katchi', 'United States of India Party', 'Universal Brotherhood Movement', 'Valamaana  Tamizhagam   Katchi']

Parties in 2026 only: 57
["ALL PENSIONER'S PARTY", 'Ahila India Dhayaga Makkal Munnetra Katchi', 'Akila Inthiya Makkal Marumalarchi Kazhakam', 'All India Forward Bloc', 'All India Majlis-E-Inquilab-E-Millat', 'All India Puratchi Thalaivar Makkal Munnettra Kazhagam', 'Anaithinthiya Anna Dravida Makkal Seyal katchi', 'Anna Makkal Katchi', 'Anti Corruption Dynamic Party', 'Bahujan Samaj Party', 'Bharat Jan Chikitsa Party', 'Bharatha Makkal Katchi', 'Communist Party of India (Marxist-Leninist) (Liberation)', 'Communist Party of India (Marxist-Leninist) Red Star', 'Democratic National Allegiance', 'Desa Makkal Munnetrak Kazhagam', 'Dravida Jananayaga Makkal Katchi', 'Indhu Dravida Makkal Katchi', 'India Suyarajya Party', 'Indian Christian Front', 'Indian National League', 'Makkal Arasial Katchi', 'Makkal Munnetra Katchi', 'Makkal Murasu Katchi', 'Makkal Sananayaga Kudiyarasu Katchi', 'Mannin Maithargal Kazhagam', 'Nam Naadu Nam Makkal Nam Ethirkaalam Katchi', 'National Maha Sabha Party', 'Nationalist Janshakti Party', "New Generation People's Party", 'Our Mahathma National Party', 'Parivartan Rajniti Party', 'Party for the Rights of Other backward Classes', 'Periyar Ambedkar Munnetra Kazhagam (PAMK)', 'Proutist Sarva Samaj', 'Puthiya Makkal Tamil Desam Katchi', 'Rashtriya Janata Dal', 'Rashtriya Samaj Dal (R)', 'Republican Party of India', 'Republican Party of India (A)', 'Republican Party of India (Athawale)', 'Socialist Unity Centre Of India (COMMUNIST)', 'TVK', 'Tamil Manila Murpokku Dravida Kazhagam', 'Tamilaga Makkal Nala Katchi', 'Tamilar Makkal Katchi', 'Tamizhaga Vaazhvurimai Katchi', 'Thakkam Katchi', 'Thamizh Desiya Munnetra Kazhagam', 'Thamizh Perarasu Katchi', 'Thamizhaga Dravidar Katchi', 'Thamizhaka Padaippalar Makkal Katchi', 'Vada Tamil Nadu Munnetra Katchi', 'Vanchit Bahujan Aaghadi', 'Viduthalai Kalam Katchi', 'Viro Ke Vir Indian Party', 'Vishwa Tamil Kazhagam']

Common to both: 48

In [19]:
# 4.6 Constituency name spelling drift — confirm we should join on ac_number
# Compare constituency names at the same ac_number across years
merged_names = df_2021[['ac_number','constituency']].drop_duplicates().merge(
    df_2026[['ac_number','constituency']].drop_duplicates(),
    on='ac_number',
    suffixes=('_2021','_2026')
)

# Show rows where the spelling differs
mismatches = merged_names[merged_names['constituency_2021'] != merged_names['constituency_2026']]
print(f"Constituencies with name-spelling drift between 2021 and 2026: {len(mismatches)}")
print()
print(mismatches.head(20))

Constituencies with name-spelling drift between 2021 and 2026: 34

     ac_number        constituency_2021       constituency_2026
0            1             Gummidipundi           Gummidipoondi
10          11  Dr. Radhakrishnan Nagar  Dr.Radhakrishnan Nagar
23          24       Theayagaraya Nagar        Thiyagarayanagar
34          35            Maduranthakam            Madurantakam
37          38                 Arakonam               Arakkonam
38          39               Sholinghur               Sholingur
45          46               Gudiyatham              Gudiyattam
46          47             Vaniayambadi             Vaniyambadi
56          57                 Palacode                Palacodu
59          60         Pappireddippatti         Pappireddipatti
73          74               Villupuram              Viluppuram
76          77               Ulundurpet           Ulundurpettai
77          78             Rishivandiam           Rishivandiyam
85          86                  Edapadi                Edappadi
92          93            Sendamangalam          Senthamangalam
95          96             Tiruchengode            Tiruchengodu
99         100              Modakurichi            Modakkurichi
110        111             Mettupalayam           Mettuppalayam
117        118         Coimbatore North      Coimbatore (North)
119        120         Coimbatore South      Coimbatore (South)

In [20]:
# 4.7 Final cross-check — does master match the result files?
# Master + 2021 join sanity
check = df_master.merge(
    df_2021.drop_duplicates('ac_number')[['ac_number','reserved','region']],
    on='ac_number',
    suffixes=('_master','_2021')
)

# Do master.reserved and 2021.reserved always agree?
reserved_match = (check['reserved_master'] == check['reserved_2021']).all()
region_match = (check['region_master'] == check['region_2021']).all()

print(f"Master.reserved matches 2021.reserved for all 234 ACs: {reserved_match}")
print(f"Master.region matches 2021.region for all 234 ACs: {region_match}")

Master.reserved matches 2021.reserved for all 234 ACs: True
Master.region matches 2021.region for all 234 ACs: True

## Step 5 — Build the Winners Table (the foundation)

In [22]:
# 5.1 Define MAJOR_PARTIES and the normalization function

# the parties we track explicitly. Everything else → 'OTHERS'.
MAJOR_PARTIES = {
    'DMK',         # Dravida Munnetra Kazhagam
    'AIADMK',      # All India Anna Dravida Munnetra Kazhagam
    'TVK',         # Tamilaga Vettri Kazhagam — new 2026 entrant
    'BJP',         # Bharatiya Janata Party
    'INC',         # Indian National Congress
    'PMK',         # Pattali Makkal Katchi
    'VCK',         # Viduthalai Chiruthaigal Katchi
    'NTK',         # Naam Tamilar Katchi
    'CPI',         # Communist Party of India
    'CPI(M)',      # Communist Party of India (Marxist)
    'DMDK',        # Desiya Murpokku Dravida Kazhagam
    'AMMK',        # Amma Makkal Munnetra Kazhagam
    'MDMK',        # Marumalarchi Dravida Munnetra Kazhagam
    'IND',         # Independent candidates
    'NOTA',        # None Of The Above
}

def normalize_party(p):
    """Bucket any party not in MAJOR_PARTIES into 'OTHERS'."""
    return p if p in MAJOR_PARTIES else 'OTHERS'

# Apply to both years — create a NEW column, don't overwrite raw 'party'
df_2021['party_clean'] = df_2021['party'].apply(normalize_party)
df_2026['party_clean'] = df_2026['party'].apply(normalize_party)

print("Normalization applied. Sample of new column:")
df_2026[['constituency','candidate','party','party_clean','votes']].head(10)

Normalization applied. Sample of new column:

,constituency,candidate,party,party_clean,votes
0,Gummidipoondi,S.VIJAYAKUMAR,TVK,TVK,94320
1,Gummidipoondi,SUDHAKAR.V,AIADMK,AIADMK,66375
2,Gummidipoondi,T.J.GOVINDARAJAN,DMK,DMK,62492
3,Gummidipoondi,"R.SRIDAR. B.L.,",NTK,NTK,4756
4,Gummidipoondi,NOTA,NOTA,NOTA,937
5,Gummidipoondi,M.JAGADEESAN,Bahujan Samaj Party,OTHERS,697
6,Gummidipoondi,SDK SANKAR,Aanaithinthiya Jananayaka Pathukappu Kazhagam,OTHERS,599
7,Gummidipoondi,G.RANJITH B.SC.L.L.B,IND,IND,503
8,Gummidipoondi,K. CHANDRA SEKAR,Veerath Thiyagi Viswanathadoss Thozhilalarkal ...,OTHERS,336
9,Gummidipoondi,D.SUDHAKAR,IND,IND,321

In [23]:
# 5.2 Verify the normalization didn't break anything

print(f"=== 2021 party_clean counts ===")
print(df_2021['party_clean'].value_counts())
print(f"\n=== 2026 party_clean counts ===")
print(df_2026['party_clean'].value_counts())

=== 2021 party_clean counts ===
party_clean
IND       2073
OTHERS    1001
NTK        234
NOTA       234
AIADMK     191
DMK        188
AMMK       165
DMDK        60
INC         25
PMK         23
BJP         20
VCK          6
CPI          6
CPI(M)       6
Name: count, dtype: int64

=== 2026 party_clean counts ===
party_clean
IND       2209
OTHERS     881
NTK        234
NOTA       234
TVK        233
DMK        176
AIADMK     172
BJP         33
INC         28
PMK         18
AMMK        11
DMDK        10
VCK          8
CPI(M)       5
CPI          5
Name: count, dtype: int64

In [24]:
# 5.3 Build the winners table - the function

def build_winners_table(df, year_label):
    """
    Build one-row-per-AC table with:
      winner + runner-up info, margin, regional metadata.
    """
    # Sort: lowest ac_number first, then highest votes first.
    # That puts the winner at the top of each AC's group.
    s = df.sort_values(['ac_number', 'votes'], ascending=[True, False]).copy()

    # rank: 1 = winner, 2 = runner-up, 3+ = also-rans
    s['rank'] = s.groupby('ac_number').cumcount() + 1

    # Pull out winner rows
    winners = s[s['rank'] == 1][['ac_number', 'constituency', 'reserved', 'region',
                                   'candidate', 'party', 'party_clean', 'votes']].copy()
    winners = winners.rename(columns={
        'candidate':   'winner_candidate',
        'party':       'winner_party_raw',
        'party_clean': 'winner_party',
        'votes':       'winner_votes'
    })

    # Pull out runner-up rows
    runners = s[s['rank'] == 2][['ac_number', 'candidate', 'party_clean', 'votes']].copy()
    runners = runners.rename(columns={
        'candidate':   'runner_up_candidate',
        'party_clean': 'runner_up_party',
        'votes':       'runner_up_votes'
    })

    # Join winners + runners on ac_number
    out = winners.merge(runners, on='ac_number', how='left')

    # Total valid votes in the AC (denominator for margin %)
    totals = df.groupby('ac_number')['votes'].sum().rename('total_valid_votes').reset_index()
    out = out.merge(totals, on='ac_number')

    # Margin metrics
    out['margin']                  = out['winner_votes'] - out['runner_up_votes']
    out['margin_pct']              = (out['margin'] / out['total_valid_votes']) * 100
    out['winner_vote_share_pct']   = (out['winner_votes'] / out['total_valid_votes']) * 100

    # Add the year tag (useful when we concat the two tables later)
    out['year'] = year_label

    # Order columns nicely
    col_order = ['year', 'ac_number', 'constituency', 'region', 'reserved',
                 'winner_candidate', 'winner_party', 'winner_party_raw', 'winner_votes',
                 'runner_up_candidate', 'runner_up_party', 'runner_up_votes',
                 'margin', 'margin_pct', 'winner_vote_share_pct', 'total_valid_votes']
    return out[col_order]

winners_2021 = build_winners_table(df_2021, 2021)
winners_2026 = build_winners_table(df_2026, 2026)

print(f"winners_2021 shape: {winners_2021.shape}")
print(f"winners_2026 shape: {winners_2026.shape}")

winners_2021 shape: (234, 16)
winners_2026 shape: (234, 16)

In [25]:
# 5.4 Peek at the winners table

winners_2026.head(10)

,year,ac_number,constituency,region,reserved,winner_candidate,winner_party,winner_party_raw,winner_votes,runner_up_candidate,runner_up_party,runner_up_votes,margin,margin_pct,winner_vote_share_pct,total_valid_votes
0,2026,1,Gummidipoondi,Chennai Metro,GEN,S.VIJAYAKUMAR,TVK,TVK,94320,SUDHAKAR.V,AIADMK,66375,27945,12.018218,40.563904,232522
1,2026,2,Ponneri,Chennai Metro,SC,DR.RAVI.M.S,TVK,TVK,110439,DURAI CHANDRASEKAR,INC,54671,55768,24.587005,48.690365,226819
2,2026,3,Tiruttani,Chennai Metro,GEN,G.HARI,AIADMK,AIADMK,89169,M.SATHYA KUMAR,TVK,83376,5793,2.425900,37.340765,238798
3,2026,4,Thiruvallur,Chennai Metro,GEN,DR. T. ARUNKUMAR,TVK,TVK,92190,V.G. RAAJENDRAN,DMK,67430,24760,10.935043,40.714929,226428
4,2026,5,Poonamallee,Chennai Metro,SC,PRAKASAM.R,TVK,TVK,161309,KRISHNASWAMY.A,DMK,88569,72740,23.548531,52.221474,308894
5,2026,6,Avadi,Chennai Metro,GEN,R.RAMESH KUMAR,TVK,TVK,180384,S.M.NASAR,DMK,104073,76311,22.054884,52.133351,346005
6,2026,7,Maduravoyal,Chennai Metro,GEN,RHEVANTH CHARAN,TVK,TVK,141725,GANAPATHY. K,DMK,80216,61509,20.943369,48.256337,293692
7,2026,8,Ambattur,Chennai Metro,GEN,BALAMURUGAN.G,TVK,TVK,133339,DR A.P. POORNIMA,DMK,74558,58781,22.609294,51.286992,259986
8,2026,9,Madavaram,Chennai Metro,GEN,M.L.VIJAYPRABHU,TVK,TVK,190462,S.SUDHARSANAM,DMK,95477,94985,26.239095,52.614103,361998
9,2026,10,Thiruvottiyur,Chennai Metro,GEN,SENTHIL KUMAR. N,TVK,TVK,110067,SUNDARARAJ. L,CPI(M),56503,53564,25.865333,53.149869,207088

In [26]:
# 5.5 Sanity checks on the winners table

print("=== Sanity checks ===\n")

# Check 1: exactly 234 winners per year
print(f"2021 winners count: {len(winners_2021)}  (should be 234)")
print(f"2026 winners count: {len(winners_2026)}  (should be 234)")

# Check 2: all ACs unique (no AC appearing twice)
print(f"\n2021 unique ACs: {winners_2021['ac_number'].nunique()}  (should be 234)")
print(f"2026 unique ACs: {winners_2026['ac_number'].nunique()}  (should be 234)")

# Check 3: every margin should be > 0 (winner had more votes than runner-up)
print(f"\n2021 rows with margin <= 0: {(winners_2021['margin']<=0).sum()}  (should be 0)")
print(f"2026 rows with margin <= 0: {(winners_2026['margin']<=0).sum()}  (should be 0)")

# Check 4: winner_vote_share_pct should be between 0 and 100
print(f"\n2021 winner vote share range: {winners_2021['winner_vote_share_pct'].min():.1f}% to {winners_2021['winner_vote_share_pct'].max():.1f}%")
print(f"2026 winner vote share range: {winners_2026['winner_vote_share_pct'].min():.1f}% to {winners_2026['winner_vote_share_pct'].max():.1f}%")

# Check 5: any NaN values in the table?
print(f"\n2021 NaN columns: {winners_2021.columns[winners_2021.isnull().any()].tolist() or 'None ✅'}")
print(f"2026 NaN columns: {winners_2026.columns[winners_2026.isnull().any()].tolist() or 'None ✅'}")

=== Sanity checks ===

2021 winners count: 234  (should be 234)
2026 winners count: 234  (should be 234)

2021 unique ACs: 234  (should be 234)
2026 unique ACs: 234  (should be 234)

2021 rows with margin <= 0: 0  (should be 0)
2026 rows with margin <= 0: 0  (should be 0)

2021 winner vote share range: 33.5% to 72.1%
2026 winner vote share range: 29.3% to 58.9%

2021 NaN columns: None ✅
2026 NaN columns: None ✅

In [27]:
# 5.6 Save the winners tables to processed/

# Save both years and a combined version for later use
PROCESSED = REPO / "data" / "processed"
PROCESSED.mkdir(exist_ok=True)

winners_2021.to_csv(PROCESSED / "winners_2021.csv", index=False)
winners_2026.to_csv(PROCESSED / "winners_2026.csv", index=False)

# Combined long-format version (both years stacked) — useful for charts
winners_long = pd.concat([winners_2021, winners_2026], ignore_index=True)
winners_long.to_csv(PROCESSED / "winners_combined.csv", index=False)

print(f"Saved to {PROCESSED}:")
for f in sorted(PROCESSED.iterdir()):
    print(f"  {f.name}  ({f.stat().st_size:,} bytes)")

Saved to e:\Help-AtliQ-Media-to-Decode-2026\tn-election-2026-decoded\data\processed:
  winners_2021.csv  (32,860 bytes)
  winners_2026.csv  (32,515 bytes)
  winners_combined.csv  (65,160 bytes)

In [28]:
# Did MDMK contest under a different label?
mdmk_pattern = 'MDMK|Marumalarchi'
print("2021 labels matching MDMK/Marumalarchi:", df_2021[df_2021['party'].str.contains(mdmk_pattern, case=False, na=False)]['party'].unique())
print("2026 labels matching MDMK/Marumalarchi:", df_2026[df_2026['party'].str.contains(mdmk_pattern, case=False, na=False)]['party'].unique())

2021 labels matching MDMK/Marumalarchi: <ArrowStringArray>
['Kongu  Desa  Marumalarchi  Makkal  Katchi']
Length: 1, dtype: str
2026 labels matching MDMK/Marumalarchi: <ArrowStringArray>
['Akila Inthiya Makkal Marumalarchi Kazhakam']
Length: 1, dtype: str